name: snvoter
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7.7
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pysam>=0.15.4
  - tqdm>=4.44.1
  - scipy==1.4.1
  - scikit-learn==0.21.3
  - tensorflow==2.1.0
  - keras==2.2.4
  - matplotlib>=3.2.1
  - multiprocess>=0.70.10
